-- 사내 운영환경에서 사용할 쿼리를 여기에 넣으세요.
-- data.py의 load_df_from_company_db()가 이 파일을 읽어 executeSQL(query)에 넘깁니다.
--
-- 예시:
-- SELECT
--   출원번호,
--   제목,
--   대분류,
--   중분류,
--   현상,
--   조치,
--   정답_판단결과
-- FROM your_table
-- WHERE 등록일 >= '2026-01-01';

